---
- hosts: localhost
  name: Setup DC and folders
  gather_facts: false
  vars_files:
    - ../answerfile.yml
    - ../answerfile-DC.yml

  tasks:
    - name: Provide information about vCenter
      vmware_about_info:
        hostname: '{{ vcenter_hostname }}.{{ dnsdomain }}'
        validate_certs: no
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
      delegate_to: localhost
      register: vcenter_about_info

    - name: Create Datacenter
      vmware_datacenter:
        validate_certs: no
        hostname: '{{ vcenter_hostname }}.{{ dnsdomain }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        datacenter_name: '{{ datacenter_name }}'
        state: present
      delegate_to: localhost

    - name: Create Clusters - All
      vmware_cluster:
        validate_certs: no
        hostname: '{{ vcenter_hostname }}.{{ dnsdomain }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        datacenter_name: '{{ datacenter_name }}'
        cluster_name: "{{ item }}"
        enable_ha: False
        # ha_vm_monitoring: vmMonitoringOnly
        enable_drs: True
        drs_default_vm_behavior: partiallyAutomated
      register: cl_result
      delegate_to: localhost
      with_items: '{{ cluster_name_list }}'


    # - name: Create Host Folder - COMPUTE
    #   vcenter_folder:
    #     validate_certs: no
    #     hostname: '{{ vcenter_hostname }}.{{ domain }}'
    #     username: '{{ vcenter_username }}'
    #     password: '{{ vcenter_password }}'
    #     datacenter_name: '{{ datacenter_name }}'
    #     folder_name: '{{ host_folder_name_compute }}'
    #     folder_type: host
    #     state: present
    #   register: vm_folder_creation_result
    #   delegate_to: localhost

    - name: Create VM Folders
      vcenter_folder:
        validate_certs: no
        hostname: '{{ vcenter_hostname }}.{{ dnsdomain }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        datacenter_name: '{{ datacenter_name }}'
        folder_name: '{{ item }}'
        folder_type: vm
        state: present
      register: vm_folder_creation_result
      delegate_to: localhost
      with_items: '{{ vm_folder_names }}'
